# Generated by Django 5.1.1 on 2024-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                (
                    "subtitle",
                    models.CharField(max_length=200, verbose_name="Subtitulo"),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "image",
                    models.ImageField(upload_to="services", verbose_name="Imagen"),
                ),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de actualozación"
                    ),
                ),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ["-created"],
            },
        ),
    ]
