# Generated by Django 5.1.1 on 2024-10-30 17:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenido"),
                ),
                ("order", models.SmallIntegerField(default=0, verbose_name="Orden")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "pagina",
                "verbose_name_plural": "paginas",
                "ordering": ["order", "title"],
            },
        ),
    ]
