# Generated by Django 5.1.1 on 2024-10-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="get_post", to="blog.category", verbose_name="Categorias"
            ),
        ),
    ]
